### PR TITLE
fcl: use patch instead of forked tarball

### PR DESCRIPTION
**Pull request by scpeters**
Alternative to 30d94c434c26469493730f3b4b4d19c003d214df

### CODE REVIEW

**Comment by scpeters** [comment]
Also, I don't think this patch should be necessary, so perhaps we can try to debug what the original issue was?

**Comment by jslee02** [comment]
When I try to install libccd and fcl:
```
brew remove libccd
brew remove fcl
brew cleanup
brew update
brew linstall libccd
brew install https://raw.githubusercontent.com/dartsim/homebrew-dart/fcl_original/fcl.rb
```
I get this error:
```
==> Downloading https://github.com/flexible-collision-library/fcl/archive/0.3.2.
Already downloaded: /Library/Caches/Homebrew/fcl-0.3.2.tar.gz
==> cmake . -DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/fcl/0.3.2 -DCMAKE_BUILD_TYP
  Libccd is required by FCL


-- Configuring incomplete, errors occurred!
```

**Comment by scpeters** [comment]
What does `brew info libccd` say? Mine says:
~~~
libccd: stable 2.0 (bottled), HEAD
http://libccd.danfis.cz
/usr/local/Cellar/libccd/2.0 (10 files, 128K) *
  Built from source
From: https://github.com/homebrew/homebrew-science/blob/master/libccd.rb
==> Dependencies
Build: cmake ✔
~~~

**Comment by jslee02** [comment]
Mine says:
```
libccd: stable 2.0 (bottled), HEAD
http://libccd.danfis.cz
/usr/local/Cellar/libccd/2.0 (10 files, 132K) *
  Poured from bottle
From: https://github.com/homebrew/homebrew-science/blob/master/libccd.rb
==> Dependencies
Build: cmake ✔
```

**Comment by scpeters** [comment]
It looks like it fails to find `libccd` with `pkg-config`. If you `brew install fcl`, it should work, since homebrew sets up the paths for you. Can you try setting the following environment variable and running again:
~~~
export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig:$PKG_CONFIG_PATH
~~~

**Comment by jslee02** [comment]
I still get same error.
```
Jeongseoks-MacBook-Pro:build jeongseoklee$ export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig:$PKG_CONFIG_PATH
Jeongseoks-MacBook-Pro:build jeongseoklee$ brew install https://raw.githubusercontent.com/dartsim/homebrew-dart/fcl_original/fcl.rb
######################################################################## 100.0%
==> Downloading https://github.com/flexible-collision-library/fcl/archive/0.3.2.
Already downloaded: /Library/Caches/Homebrew/fcl-0.3.2.tar.gz
==> cmake . -DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/fcl/0.3.2 -DCMAKE_BUILD_TYP
  Libccd is required by FCL


-- Configuring incomplete, errors occurred!
```

**Comment by jslee02** [comment]
Found `ccd.pc`: 
```
Jeongseoks-MacBook-Pro:build jeongseoklee$ find /usr/ -name 'ccd.pc'
/usr//local/Cellar/libccd/2.0/lib/pkgconfig/ccd.pc
/usr//local/lib/pkgconfig/ccd.pc
find: /usr//sbin/authserver: Permission denied
```

**Comment by jslee02** [comment]
It's strange why fcl cannot find `ccd.pc`.

Here is what I got:
```
Jeongseoks-MacBook-Pro:pkgconfig jeongseoklee$ find /usr -name 'ccd.pc'
/usr/local/Cellar/libccd/2.0/lib/pkgconfig/ccd.pc
/usr/local/lib/pkgconfig/ccd.pc

Jeongseoks-MacBook-Pro:pkgconfig jeongseoklee$ echo ${PKG_CONFIG_PATH}
/usr/local/lib/pkgconfig/:/usr/local/Cellar/libccd/2.0/lib/pkgconfig/

Jeongseoks-MacBook-Pro:pkgconfig jeongseoklee$ brew install https://raw.githubusercontent.com/dartsim/homebrew-dart/fcl_original/fcl.rb
######################################################################## 100.0%
==> Downloading https://github.com/flexible-collision-library/fcl/archive/0.3.2.
Already downloaded: /Library/Caches/Homebrew/fcl-0.3.2.tar.gz
==> cmake . -DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/fcl/0.3.2 -DCMAKE_BUILD_TYP
  Libccd is required by FCL


-- Configuring incomplete, errors occurred!
```

**Comment by jslee02** [comment]
Now I get it! `pkg-config` is not installed. I could install `fcl` with `pkg-config` correctly.

Should we create a patch for 'fcl' to have `pkg-config` as a dependency?

**Comment by jslee02** [comment]
I looks fine now. I could install `fcl` on clean system.

**Comment by scpeters** [comment]
+1

**Pull request merged**
