### PR TITLE
Travis CI

### PR DESCRIPTION
**Pull request by jslee02**

### CODE REVIEW

**Comment by scpeters** [comment]
Nice, looks familiar =)

**Comment by jslee02** [comment]
Yeah, I found very nice reference!

Btw, I don't understand why the builds are not started.

**Comment by scpeters** [comment]
I just added another check to verify that patches apply cleanly and also to make brew fetch a little quieter so it doesn't fill the log file too fast:

* https://github.com/osrf/homebrew-simulation/commit/f3cad8c9ab2639d5981418b96002d02a1d6955ea
* https://github.com/osrf/homebrew-simulation/commit/9cf102dad9cd0ba29319f6b6bee8dccee24366e3
* https://github.com/travis-ci/travis-ci/issues/4936

**Comment by jslee02** [comment]
It seems good to merge now. Thanks @scpeters !

**Pull request merged**
